### ISSUE TITLE
Please update for Plasma 6

### ISSUE THREAD

**Issue by joobert** [Gerrnperl/ksysguard-colored-text#3]
Display style not appearing on Plasma 6

**Comment by Gerrnperl** [comment]
Hello.
I made some changes. I have tested it to work on Plasma 6 on KDE Neon.

You can download and try it at https://www.pling.com/p/1972690/ by selecting org.gerrnperl.text-v0.3.tar.gz.

I thought migrating from Plasma 5 to Plasma 6 would require a lot of work, which is why I'm late with this update.

But it looks like it doesn't take much work to migrate, Plasma 6 added a format check that requires me to set `"KPackageStructure": "KSysguard/SensorFace"`, which breaks compatibility.I wonder why Plasma doesn't provide such a backward compatibility.

Please install this version and try it, I hope it works, thank you.

❤️

**Comment by joobert** [comment]
> Hello. I made some changes. I have tested it to work on Plasma 6 on KDE Neon.
> 
> You can download and try it at https://www.pling.com/p/1972690/ by selecting org.gerrnperl.text-v0.3.tar.gz.
> 
> I thought migrating from Plasma 5 to Plasma 6 would require a lot of work, which is why I'm late with this update.
> 
> But it looks like it doesn't take much work to migrate, Plasma 6 added a format check that requires me to set `"KPackageStructure": "KSysguard/SensorFace"`, which breaks compatibility.I wonder why Plasma doesn't provide such a backward compatibility.
> 
> Please install this version and try it, I hope it works, thank you.
> 
> ❤️

Great! Thanks for doing that. Testing now and found a few issues:
- Options menu is missing. Cannot configure the style whatsoever. No way to change text color (dynamic R/G or static color), bar position (horizontal/vertical), etc.
- Usage bar is hidden at certain panel heights/not dynamically positioned. Originally I thought the bar was completely missing (at panel height 26px), but then I made my panel height taller and the bar started to appear. This was not an issue in the Plasma 5 version, as my panel height was the exact same at 26px tall, and the bar was fully present (and centered).
- Too biased towards bottom margin. Probably related to the above issue regarding panel height. Once the usage bar finally was fully visible at panel height of 32px, it aligned right above the bottom border of the panel. I assume that this is because the usage bar is not being accounted for size-wise when the plasmoid is looking to find its anchor at the center of the panel. When compared with the screenshots taken from the previous version (where it's clear that the center is the anchor), it becomes pretty obvious, especially at smaller panel sizes.

**Comment by Gerrnperl** [comment]
Thank you for the test. 😀

- The configuration page has been fixed.
- The layout should now be guaranteed to be centered.
- And I've also provided some `size` configuration options that should work for panels of different heights.
![Screenshot](https://github.com/Gerrnperl/ksysguard-colored-text/assets/64595686/c522ee03-f72b-47eb-8a33-ccabe39ad0e9)

**Comment by joobert** [comment]
Awesome! Seems to be working great now, thank you
